from sqlalchemy.orm import Session, joinedload

from app.core.sequences import next_sequence_number
from app.models.receipt import Receipt
from app.models.voucher import Voucher, VoucherLine, VoucherType
from app.schemas.voucher import VoucherCreate

_TYPE_PREFIX = {
    VoucherType.RECEIPT: "RV",
    VoucherType.PAYMENT: "PV",
    VoucherType.JOURNAL: "JV",
    VoucherType.CONTRA: "CV",
}


def _next_voucher_no(db: Session, voucher_type: VoucherType) -> str:
    prefix = f"{_TYPE_PREFIX[voucher_type]}-"
    return next_sequence_number(db, Voucher.voucher_no, prefix, 5)


def list_vouchers(
    db: Session,
    voucher_type: str | None = None,
    project_id: int | None = None,
) -> list[Voucher]:
    query = db.query(Voucher).options(
        joinedload(Voucher.lines).joinedload(VoucherLine.account)
    )
    if voucher_type is not None:
        query = query.filter(Voucher.voucher_type == voucher_type)
    if project_id is not None:
        query = query.filter(Voucher.project_id == project_id)
    return query.order_by(Voucher.id.desc()).all()


def get_voucher(db: Session, voucher_id: int) -> Voucher | None:
    return (
        db.query(Voucher)
        .options(joinedload(Voucher.lines).joinedload(VoucherLine.account))
        .filter(Voucher.id == voucher_id)
        .first()
    )


def create_voucher(db: Session, voucher_in: VoucherCreate) -> Voucher:
    db_voucher = Voucher(
        voucher_no=_next_voucher_no(db, voucher_in.voucher_type),
        voucher_type=voucher_in.voucher_type,
        voucher_date=voucher_in.voucher_date,
        project_id=voucher_in.project_id,
        narration=voucher_in.narration,
    )
    db.add(db_voucher)
    db.flush()

    for line in voucher_in.lines:
        db.add(
            VoucherLine(
                voucher_id=db_voucher.id,
                account_id=line.account_id,
                debit=line.debit,
                credit=line.credit,
                narration=line.narration,
            )
        )

    db.commit()
    db.refresh(db_voucher)
    return get_voucher(db, db_voucher.id)


def delete_voucher(db: Session, db_voucher: Voucher) -> None:
    receipts = db.query(Receipt).filter(Receipt.voucher_id == db_voucher.id).all()
    if receipts:
        refs = ", ".join(r.receipt_no for r in receipts)
        raise ValueError(
            f"This voucher was auto-generated by {len(receipts)} receipt(s) and cannot be "
            f"deleted directly: {refs}. Delete the receipt(s) instead — the linked voucher "
            f"will be removed automatically."
        )
    db.delete(db_voucher)
    db.commit()
