"""add reason to material_issues

Revision ID: 1683068b30d5
Revises: e2fff812d9e7
Create Date: 2026-08-30 14:14:59.058207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1683068b30d5'
down_revision: Union[str, None] = 'e2fff812d9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_issues', sa.Column('reason', sa.Enum('SITE_CONSUMPTION', 'DAMAGED', name='materialissuereason'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_issues', 'reason')
    # ### end Alembic commands ###
