"""add customer accounts table

Revision ID: 1a6dab3ddd14
Revises: 4d0a445629e5
Create Date: 2026-08-29 18:42:21.558252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6dab3ddd14'
down_revision: Union[str, None] = '4d0a445629e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allottee_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allottee_id'], ['allottees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allottee_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_accounts')
    # ### end Alembic commands ###
