"""add total_floors to projects

Revision ID: 1e61fef35484
Revises: eac0a4d2f22f
Create Date: 2026-08-31 14:14:47.301862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e61fef35484'
down_revision: Union[str, None] = 'eac0a4d2f22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_floors', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_floors')
    # ### end Alembic commands ###
