"""add cheque status and clearing date to receipts

Revision ID: 201b85a940e8
Revises: 8e052316e22e
Create Date: 2026-09-03 15:02:36.650075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201b85a940e8'
down_revision: Union[str, None] = '8e052316e22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('cheque_clearing_date', sa.Date(), nullable=True))
    op.add_column('receipts', sa.Column('cheque_status', sa.Enum('PENDING', 'CLEARED', 'BOUNCED', name='chequestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'cheque_status')
    op.drop_column('receipts', 'cheque_clearing_date')
    # ### end Alembic commands ###
