"""add booking agents and commission payouts

Revision ID: 2d43be3c4677
Revises: 6a34dfbb2f5f
Create Date: 2026-08-25 10:09:02.933440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d43be3c4677'
down_revision: Union[str, None] = '6a34dfbb2f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.Column('default_commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code')
    )
    op.create_table('commission_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_no', sa.String(length=30), nullable=False),
    sa.Column('payout_date', sa.Date(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['booking_agents.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_no')
    )
    op.add_column('bookings', sa.Column('booking_agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'booking_agents', ['booking_agent_id'], ['id'])
    op.drop_column('bookings', 'booking_agent_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_agent_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'booking_agent_id')
    op.drop_table('commission_payouts')
    op.drop_table('booking_agents')
    # ### end Alembic commands ###
