"""add booking extra charges as multiple line items

Revision ID: 32daf5bffc93
Revises: 947d4262381b
Create Date: 2026-09-15 10:22:11.654907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32daf5bffc93'
down_revision: Union[str, None] = '947d4262381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_extra_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('schedule_line_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('EAST_FACING', 'WEST_FACING', 'OPEN', 'ROAD_FACING', 'CORNER', 'WATER', 'ELECTRICITY', 'DOCUMENTS', 'OTHER', name='extrachargesreason'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['schedule_line_id'], ['payment_schedule_lines.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('bookings', 'extra_charges_reason')
    op.drop_column('bookings', 'extra_charges_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('extra_charges_amount', mysql.DECIMAL(precision=18, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    op.add_column('bookings', sa.Column('extra_charges_reason', mysql.ENUM('EAST_FACING', 'WEST_FACING', 'OPEN', 'ROAD_FACING', 'WATER', 'ELECTRICITY', 'OTHER', collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_table('booking_extra_charges')
    # ### end Alembic commands ###
