"""add extra charges to bookings

Revision ID: 49cdcb16bc84
Revises: 89bad6782708
Create Date: 2026-09-09 18:29:29.276555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cdcb16bc84'
down_revision: Union[str, None] = '89bad6782708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('extra_charges_amount', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('extra_charges_reason', sa.Enum('EAST_FACING', 'WEST_FACING', 'OPEN', 'ROAD_FACING', 'WATER', 'ELECTRICITY', 'OTHER', name='extrachargesreason'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'extra_charges_reason')
    op.drop_column('bookings', 'extra_charges_amount')
    # ### end Alembic commands ###
