"""support refund installments via refund_payments table

Revision ID: 5b2e33fe933e
Revises: dfd0437ab014
Create Date: 2026-09-15 11:00:05.787527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b2e33fe933e'
down_revision: Union[str, None] = 'dfd0437ab014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate doesn't pick up added enum members on a native MySQL
    # ENUM column, so widen it explicitly first.
    op.alter_column(
        'refunds', 'status',
        existing_type=sa.Enum('PENDING', 'PAID', name='refundstatus'),
        type_=sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', name='refundstatus'),
        existing_nullable=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cash_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('refunds_ibfk_4', 'refunds', type_='foreignkey')
    op.drop_constraint('refunds_ibfk_3', 'refunds', type_='foreignkey')
    op.drop_constraint('refunds_ibfk_1', 'refunds', type_='foreignkey')
    op.drop_column('refunds', 'cash_account_id')
    op.drop_column('refunds', 'account_id')
    op.drop_column('refunds', 'voucher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('voucher_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('refunds', sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('refunds', sa.Column('cash_account_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('refunds_ibfk_1', 'refunds', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('refunds_ibfk_3', 'refunds', 'accounts', ['cash_account_id'], ['id'])
    op.create_foreign_key('refunds_ibfk_4', 'refunds', 'vouchers', ['voucher_id'], ['id'])
    op.drop_table('refund_payments')
    # ### end Alembic commands ###

    op.alter_column(
        'refunds', 'status',
        existing_type=sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', name='refundstatus'),
        type_=sa.Enum('PENDING', 'PAID', name='refundstatus'),
        existing_nullable=False,
    )
