"""add resolution tracking to material_issues

Revision ID: 68216eadc137
Revises: 1683068b30d5
Create Date: 2026-08-30 14:25:52.764717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68216eadc137'
down_revision: Union[str, None] = '1683068b30d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_issues', sa.Column('resolved', sa.Boolean(), nullable=False))
    op.add_column('material_issues', sa.Column('resolved_date', sa.Date(), nullable=True))
    op.add_column('material_issues', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_issues', 'resolution_note')
    op.drop_column('material_issues', 'resolved_date')
    op.drop_column('material_issues', 'resolved')
    # ### end Alembic commands ###
