"""add booking transfers table

Revision ID: 68816e5a782c
Revises: c1d4e8f2a6b7
Create Date: 2026-09-07 12:55:18.235116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68816e5a782c'
down_revision: Union[str, None] = 'c1d4e8f2a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_no', sa.String(length=30), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('from_allottee_id', sa.Integer(), nullable=False),
    sa.Column('to_allottee_id', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['from_allottee_id'], ['allottees.id'], ),
    sa.ForeignKeyConstraint(['to_allottee_id'], ['allottees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_transfers')
    # ### end Alembic commands ###
