"""add land properties table

Revision ID: 7747460e72af
Revises: 86590e7870c2
Create Date: 2026-08-24 12:19:34.009185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7747460e72af'
down_revision: Union[str, None] = '86590e7870c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_ref_no', sa.String(length=30), nullable=False),
    sa.Column('property_type', sa.Enum('PLOT', 'LAND', 'COMMERCIAL_SHOP', 'SR', 'OTHER', name='propertytype'), nullable=False),
    sa.Column('area_location', sa.String(length=150), nullable=False),
    sa.Column('size_number', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('size_unit', sa.Enum('SQ_YD', 'SQ_FT', 'MARLA', 'KANAL', name='sizeunit'), nullable=False),
    sa.Column('owner_vendor', sa.String(length=150), nullable=True),
    sa.Column('purchase_rate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sale_rate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='landpropertystatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_ref_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('land_properties')
    # ### end Alembic commands ###
