"""add allottees table

Revision ID: 7c345045ac93
Revises: 7747460e72af
Create Date: 2026-08-24 12:26:03.984084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c345045ac93'
down_revision: Union[str, None] = '7747460e72af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allottees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allottee_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('tel_res', sa.String(length=30), nullable=True),
    sa.Column('office_phone', sa.String(length=30), nullable=True),
    sa.Column('fax', sa.String(length=30), nullable=True),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('referred_by', sa.String(length=150), nullable=True),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('nominee_name', sa.String(length=150), nullable=True),
    sa.Column('nominee_relation', sa.String(length=80), nullable=True),
    sa.Column('nominee_cnic', sa.String(length=20), nullable=True),
    sa.Column('nominee_picture_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allottee_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allottees')
    # ### end Alembic commands ###
