"""add revenue voucher link to bookings

Revision ID: 837f428ea6b0
Revises: 62a71a53ab2f
Create Date: 2026-08-25 10:26:13.004478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837f428ea6b0'
down_revision: Union[str, None] = '62a71a53ab2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('revenue_voucher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'vouchers', ['revenue_voucher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'revenue_voucher_id')
    # ### end Alembic commands ###
