"""add communication log table

Revision ID: 885e38a5aa57
Revises: bb9d207f46bf
Create Date: 2026-08-26 14:08:01.004629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885e38a5aa57'
down_revision: Union[str, None] = 'bb9d207f46bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', name='communicationchannel'), nullable=False),
    sa.Column('recipient_phone', sa.String(length=30), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('related_type', sa.Enum('RECEIPT', 'BOOKING', 'REFUND', 'OTHER', name='communicationrelatedtype'), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='communicationstatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
