"""add rentals tables

Revision ID: 89bad6782708
Revises: 71aa58aca937
Create Date: 2026-09-09 15:25:15.190269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bad6782708'
down_revision: Union[str, None] = '71aa58aca937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_code')
    )
    op.create_table('rent_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_no', sa.String(length=30), nullable=False),
    sa.Column('agreement_date', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('land_property_id', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TERMINATED', 'EXPIRED', name='rentagreementstatus'), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(unit_id IS NOT NULL AND land_property_id IS NULL) OR (unit_id IS NULL AND land_property_id IS NOT NULL)', name='rent_agreement_exactly_one_target'),
    sa.ForeignKeyConstraint(['land_property_id'], ['land_properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_no')
    )
    op.create_table('rent_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=30), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mode_of_payment', sa.String(length=30), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['rent_agreements.id'], ),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_table('rent_schedule_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('month_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['rent_agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent_receipt_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rent_receipt_id', sa.Integer(), nullable=False),
    sa.Column('schedule_line_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rent_receipt_id'], ['rent_receipts.id'], ),
    sa.ForeignKeyConstraint(['schedule_line_id'], ['rent_schedule_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Autogenerate doesn't diff MySQL native ENUM values — add 'RENTED' by hand.
    op.alter_column(
        'units',
        'status',
        existing_type=sa.Enum('AVAILABLE', 'BOOKED', 'SOLD', 'CANCELLED', 'ON_HOLD', name='unitstatus'),
        type_=sa.Enum('AVAILABLE', 'BOOKED', 'SOLD', 'CANCELLED', 'ON_HOLD', 'RENTED', name='unitstatus'),
        existing_nullable=False,
    )
    op.alter_column(
        'land_properties',
        'status',
        existing_type=sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='landpropertystatus'),
        type_=sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'RENTED', name='landpropertystatus'),
        existing_nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        'land_properties',
        'status',
        existing_type=sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'RENTED', name='landpropertystatus'),
        type_=sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='landpropertystatus'),
        existing_nullable=False,
    )
    op.alter_column(
        'units',
        'status',
        existing_type=sa.Enum('AVAILABLE', 'BOOKED', 'SOLD', 'CANCELLED', 'ON_HOLD', 'RENTED', name='unitstatus'),
        type_=sa.Enum('AVAILABLE', 'BOOKED', 'SOLD', 'CANCELLED', 'ON_HOLD', name='unitstatus'),
        existing_nullable=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_receipt_allocations')
    op.drop_table('rent_schedule_lines')
    op.drop_table('rent_receipts')
    op.drop_table('rent_agreements')
    op.drop_table('tenants')
    # ### end Alembic commands ###
