"""add partner expenses

Revision ID: 8e052316e22e
Revises: 979b78143fc8
Create Date: 2026-09-03 14:22:54.477229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e052316e22e'
down_revision: Union[str, None] = '979b78143fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_no', sa.String(length=30), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_no')
    )
    # ### end Alembic commands ###

    # Seed the "Partner Payable" liability account used to book amounts a
    # partner is owed for expenses they paid on the project's behalf.
    conn = op.get_bind()
    existing = conn.execute(sa.text("SELECT id FROM accounts WHERE code = '2030'")).first()
    if not existing:
        parent = conn.execute(sa.text("SELECT id FROM accounts WHERE code = '2000'")).first()
        if parent:
            conn.execute(
                sa.text(
                    "INSERT INTO accounts "
                    "(code, name, nature, is_control, parent_id, opening_debit, opening_credit, is_active) "
                    "VALUES ('2030', 'Partner Payable', 'Liability', 0, :parent_id, 0, 0, 1)"
                ),
                {"parent_id": parent[0]},
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_expenses')
    # ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM accounts WHERE code = '2030'"))
