"""add booking installment plans for mixed payment schedules

Revision ID: 947d4262381b
Revises: dfef4a91808b
Create Date: 2026-09-15 10:11:52.091457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '947d4262381b'
down_revision: Union[str, None] = 'dfef4a91808b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('booking_installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'YEARLY', name='schedulefrequency'), nullable=False),
    sa.Column('no_of_installments', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payment_schedule_lines', sa.Column('installment_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_schedule_lines', 'booking_installment_plans', ['installment_plan_id'], ['id'])

    # Data migration: each existing booking's single frequency/no_of_installments
    # becomes an equivalent 'Installments' plan, and its existing non-zero
    # schedule lines (the down payment / extra charges lines stay
    # installment_plan_id=NULL, unaffected) are re-pointed at it — no history lost.
    bind = op.get_bind()
    bookings = bind.execute(sa.text(
        "SELECT id, no_of_installments, frequency FROM bookings WHERE no_of_installments > 0"
    )).fetchall()
    for booking_id, no_of_installments, frequency in bookings:
        lines = bind.execute(
            sa.text(
                "SELECT id, amount, due_date FROM payment_schedule_lines "
                "WHERE booking_id = :bid AND installment_no >= 1"
            ),
            {"bid": booking_id},
        ).fetchall()
        if not lines:
            continue
        total_amount = sum(float(line.amount) for line in lines)
        start_date = min(line.due_date for line in lines)
        result = bind.execute(
            sa.text(
                "INSERT INTO booking_installment_plans "
                "(booking_id, label, frequency, no_of_installments, total_amount, start_date, created_at, updated_at) "
                "VALUES (:booking_id, 'Installments', :frequency, :no_of_installments, :total_amount, :start_date, NOW(), NOW())"
            ),
            {
                "booking_id": booking_id,
                "frequency": frequency,
                "no_of_installments": no_of_installments,
                "total_amount": total_amount,
                "start_date": start_date,
            },
        )
        plan_id = result.lastrowid
        bind.execute(
            sa.text(
                "UPDATE payment_schedule_lines SET installment_plan_id = :plan_id "
                "WHERE booking_id = :booking_id AND installment_no >= 1"
            ),
            {"plan_id": plan_id, "booking_id": booking_id},
        )

    op.drop_column('bookings', 'frequency')
    op.drop_column('bookings', 'no_of_installments')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_schedule_lines', type_='foreignkey')
    op.drop_column('payment_schedule_lines', 'installment_plan_id')
    op.add_column('bookings', sa.Column('no_of_installments', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('frequency', mysql.ENUM('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'YEARLY', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_table('booking_installment_plans')
    # ### end Alembic commands ###
