"""add land property payments and due dates

Revision ID: b308ad404f97
Revises: 49cdcb16bc84
Create Date: 2026-09-15 10:00:18.385233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b308ad404f97'
down_revision: Union[str, None] = '49cdcb16bc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_property_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('land_property_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('TO_SELLER', 'FROM_BUYER', name='landpropertypaymentdirection'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('mode_of_payment', sa.Enum('CASH', 'CHEQUE', 'BANK_TRANSFER', 'ONLINE', name='paymentmode'), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['land_property_id'], ['land_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('land_properties', sa.Column('seller_payment_due_date', sa.Date(), nullable=True))
    op.add_column('land_properties', sa.Column('buyer_payment_due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land_properties', 'buyer_payment_due_date')
    op.drop_column('land_properties', 'seller_payment_due_date')
    op.drop_table('land_property_payments')
    # ### end Alembic commands ###
