"""add bookings and payment schedule tables

Revision ID: b4d0eb79e9e5
Revises: c1649f32facf
Create Date: 2026-08-24 12:52:19.085655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d0eb79e9e5'
down_revision: Union[str, None] = 'c1649f32facf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_ref_no', sa.String(length=30), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('allottee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CONFIRMED', 'CANCELLED', 'POSSESSION_GIVEN', name='bookingstatus'), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('booking_agent_name', sa.String(length=150), nullable=True),
    sa.Column('agent_commission_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('down_payment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('no_of_installments', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'YEARLY', name='schedulefrequency'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allottee_id'], ['allottees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_ref_no')
    )
    op.create_table('payment_schedule_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('mode_of_payment', sa.Enum('CASH', 'CHEQUE', 'BANK_TRANSFER', 'ONLINE', name='paymentmode'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_schedule_lines')
    op.drop_table('bookings')
    # ### end Alembic commands ###
