"""add warehouses

Revision ID: cde0add671cf
Revises: feb683cfac6f
Create Date: 2026-09-02 13:04:16.191229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde0add671cf'
down_revision: Union[str, None] = 'feb683cfac6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_code')
    )
    op.add_column('grns', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grns', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('material_issues', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_issues', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('stock_ledger', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_ledger', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_ledger', type_='foreignkey')
    op.drop_column('stock_ledger', 'warehouse_id')
    op.drop_constraint(None, 'material_issues', type_='foreignkey')
    op.drop_column('material_issues', 'warehouse_id')
    op.drop_constraint(None, 'grns', type_='foreignkey')
    op.drop_column('grns', 'warehouse_id')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
