"""add refund status and make settlement accounts optional

Revision ID: dfd0437ab014
Revises: af988f261581
Create Date: 2026-09-15 10:47:25.604315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfd0437ab014'
down_revision: Union[str, None] = 'af988f261581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('status', sa.Enum('PENDING', 'PAID', name='refundstatus'), nullable=False))
    op.alter_column('refunds', 'account_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('refunds', 'cash_account_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'cash_account_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('refunds', 'account_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('refunds', 'status')
    # ### end Alembic commands ###
