"""add restocked flag to material_issues

Revision ID: eac0a4d2f22f
Revises: 68216eadc137
Create Date: 2026-08-30 14:45:45.441573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac0a4d2f22f'
down_revision: Union[str, None] = '68216eadc137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_issues', sa.Column('restocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

    # Alembic autogenerate doesn't detect MySQL native ENUM member changes, so this
    # is added by hand: StockRefType gained a RESTOCK member for vendor-replacement
    # stock movements posted when a damaged/wastage material issue is resolved.
    op.alter_column(
        'stock_ledger',
        'ref_type',
        existing_type=sa.Enum('GRN', 'ISSUE', name='stockreftype'),
        type_=sa.Enum('GRN', 'ISSUE', 'RESTOCK', name='stockreftype'),
        existing_nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_issues', 'restocked')
    # ### end Alembic commands ###

    op.alter_column(
        'stock_ledger',
        'ref_type',
        existing_type=sa.Enum('GRN', 'ISSUE', 'RESTOCK', name='stockreftype'),
        type_=sa.Enum('GRN', 'ISSUE', name='stockreftype'),
        existing_nullable=False,
    )
