"""add petty cash tables

Revision ID: f8ae9a7cf0c0
Revises: 5a2e9c1f8b4d
Create Date: 2026-09-07 12:14:24.624790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ae9a7cf0c0'
down_revision: Union[str, None] = '5a2e9c1f8b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash_floats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('float_code', sa.String(length=30), nullable=False),
    sa.Column('holder_name', sa.String(length=150), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('float_code')
    )
    op.create_table('petty_cash_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_no', sa.String(length=30), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('float_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['float_id'], ['petty_cash_floats.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_no')
    )
    op.create_table('petty_cash_topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topup_no', sa.String(length=30), nullable=False),
    sa.Column('topup_date', sa.Date(), nullable=False),
    sa.Column('float_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_from_id', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['float_id'], ['petty_cash_floats.id'], ),
    sa.ForeignKeyConstraint(['paid_from_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topup_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petty_cash_topups')
    op.drop_table('petty_cash_expenses')
    op.drop_table('petty_cash_floats')
    # ### end Alembic commands ###
