"""add status and receipt tracking to material issues

Revision ID: feb683cfac6f
Revises: 1e61fef35484
Create Date: 2026-09-02 12:34:46.104087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb683cfac6f'
down_revision: Union[str, None] = '1e61fef35484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_issues', sa.Column('status', sa.Enum('DISPATCHED', 'RECEIVED', name='materialissuestatus'), nullable=False, server_default='DISPATCHED'))
    op.add_column('material_issues', sa.Column('received_date', sa.Date(), nullable=True))
    op.add_column('material_issues', sa.Column('received_by', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_issues', 'received_by')
    op.drop_column('material_issues', 'received_date')
    op.drop_column('material_issues', 'status')
    # ### end Alembic commands ###
